package bookKeeper;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import bookKeeper.Book;
import bookKeeper.Series;
import bookKeeper.BookType;
import bookKeeper.Genre;

import bookKeeper.BookDao;
import bookKeeper.SeriesDao;
import bookKeeper.BookTypeDao;
import bookKeeper.GenreDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookDaoConfig;
    private final DaoConfig seriesDaoConfig;
    private final DaoConfig bookTypeDaoConfig;
    private final DaoConfig genreDaoConfig;

    private final BookDao bookDao;
    private final SeriesDao seriesDao;
    private final BookTypeDao bookTypeDao;
    private final GenreDao genreDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        seriesDaoConfig = daoConfigMap.get(SeriesDao.class).clone();
        seriesDaoConfig.initIdentityScope(type);

        bookTypeDaoConfig = daoConfigMap.get(BookTypeDao.class).clone();
        bookTypeDaoConfig.initIdentityScope(type);

        genreDaoConfig = daoConfigMap.get(GenreDao.class).clone();
        genreDaoConfig.initIdentityScope(type);

        bookDao = new BookDao(bookDaoConfig, this);
        seriesDao = new SeriesDao(seriesDaoConfig, this);
        bookTypeDao = new BookTypeDao(bookTypeDaoConfig, this);
        genreDao = new GenreDao(genreDaoConfig, this);

        registerDao(Book.class, bookDao);
        registerDao(Series.class, seriesDao);
        registerDao(BookType.class, bookTypeDao);
        registerDao(Genre.class, genreDao);
    }
    
    public void clear() {
        bookDaoConfig.getIdentityScope().clear();
        seriesDaoConfig.getIdentityScope().clear();
        bookTypeDaoConfig.getIdentityScope().clear();
        genreDaoConfig.getIdentityScope().clear();
    }

    public BookDao getBookDao() {
        return bookDao;
    }

    public SeriesDao getSeriesDao() {
        return seriesDao;
    }

    public BookTypeDao getBookTypeDao() {
        return bookTypeDao;
    }

    public GenreDao getGenreDao() {
        return genreDao;
    }

}
